import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ImageSearchModal from "@/components/modals/search-image";
import { ModalProvider } from "@/context/modal-context";
import { ImageProvider } from "@/context/image-context";
import AboutImageModal from "@/components/modals/about-image";
import { SearchProvider } from "@/context/search-context";
import { NavbarProvider } from "@/context/navbar-context";
import NextTopLoader from "nextjs-toploader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Farm RIO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased mx-auto font-geist`}
      >
        <NavbarProvider>
          <ModalProvider>
            <SearchProvider>
              <ImageProvider>
                <NextTopLoader
                  color="#61BEE6"
                  initialPosition={0.08}
                  crawlSpeed={200}
                  height={3}
                  crawl={true}
                  showSpinner={true}
                  easing="ease"
                  speed={200}
                  zIndex={1600}
                  showAtBottom={false}
                />
                {children}
                <ImageSearchModal />
                <AboutImageModal />
              </ImageProvider>
            </SearchProvider>
          </ModalProvider>
        </NavbarProvider>
      </body>
    </html>
  );
}
