import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ImageSearchModal from "@/components/modals/search-image";
import { ModalProvider } from "@/context/modal-context";
import { ImageProvider } from "@/context/image-context";
import AboutImageModal from "@/components/modals/about-image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Farm RIO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased container mx-auto font-geist`}
      >
        <ModalProvider>
          <ImageProvider>
            {children}
            <ImageSearchModal />
            <AboutImageModal />
          </ImageProvider>
        </ModalProvider>
      </body>
    </html>
  );
}
