export const photos = [
    {
      name: 'Vestido Floral',
      collection: 'Verão 2024',
      location: 'Copacabana, Rio de Janeiro',
      models: 'Ana Clara',
      creativeDirection: 'Joana Silva',
      photography: 'Carlos Costa',
      photographyAssistant: 'Fernanda Lima',
      film: 'Kodak Portra 400',
      styling: 'Lúcio Mendes',
      beauty: 'Mariana Rocha',
      setProduction: 'Set Design Brasil',
      executiveProduction: 'Agência XYZ',
      imagePath: '1.png',
    },
    {
      name: 'Jaqueta Oversized',
      collection: 'Outono 2024',
      location: 'Vila Madalena, SP',
      models: 'Jéssica Souza',
      creativeDirection: 'Daniela Prado',
      photography: 'Lucas Ribeiro',
      photographyAssistant: 'Ricardo Dias',
      film: 'Fuji Superia 200',
      styling: 'Carla Teixeira',
      beauty: 'Patrícia Gomes',
      setProduction: 'UrbanSet Prod.',
      executiveProduction: 'ModaCo Prod.',
      imagePath: '2.png',
    },
    {
      name: 'Conjunto Listrado',
      collection: 'Primavera 2024',
      location: 'Pelourinho, Salvador',
      models: 'Mateus Oliveira',
      creativeDirection: 'Bruno Matos',
      photography: 'Felipe Andrade',
      photographyAssistant: 'Sara Monteiro',
      film: 'Ilford HP5 Plus',
      styling: 'Débora Cruz',
      beauty: 'Lívia Santiago',
      setProduction: 'Norte Set Co.',
      executiveProduction: 'Estilo Livre',
      imagePath: '3.png',
    },
    {
      name: 'Macacão de Alfaiataria',
      collection: 'Inverno 2024',
      location: 'Centro Histórico, Porto Alegre',
      models: 'Clara Almeida',
      creativeDirection: 'Sérgio Tavares',
      photography: 'Rafaela Lopes',
      photographyAssistant: 'Guilherme Rocha',
      film: 'Cinestill 800T',
      styling: 'Tiago Martins',
      beauty: 'Júlia Sena',
      setProduction: 'Southern Light Prod.',
      executiveProduction: 'Alta Costura BR',
      imagePath: '4.png',
    },
    {
      name: 'Saia Midi Plissada',
      collection: 'Resort 2025',
      location: 'Fernando de Noronha',
      models: 'Isabela Torres',
      creativeDirection: 'Nathalia Braga',
      photography: 'Henrique Pires',
      photographyAssistant: 'Luna Carvalho',
      film: 'Kodak Ektar 100',
      styling: 'Pedro Farias',
      beauty: 'Bruna Vasques',
      setProduction: 'Ilha Studio',
      executiveProduction: 'Maré Alta Prod.',
      imagePath: '5.png',
    },
    {
      name: 'Top de Crochê',
      collection: 'Alto Verão 2024',
      location: 'Trancoso, Bahia',
      models: 'Rafaella Dias',
      creativeDirection: 'Vítor Mendes',
      photography: 'Manuela Freitas',
      photographyAssistant: 'João Lima',
      film: 'Fujicolor C200',
      styling: 'Amanda Ribeiro',
      beauty: 'Nina Ferreira',
      setProduction: 'Bahia Vibes',
      executiveProduction: 'Sol Produções',
      imagePath: '6.png',
    },
    {
      name: 'Camisa de Linho',
      collection: 'Primavera Urbana',
      location: 'Largo do Boticário, RJ',
      models: 'Enzo Barreto',
      creativeDirection: 'Helena Rocha',
      photography: 'Eduardo Nogueira',
      photographyAssistant: 'Marcela Prado',
      film: 'Kodak Gold 200',
      styling: 'Juliano Batista',
      beauty: 'Bianca Martins',
      setProduction: 'Casa Antiga Prod.',
      executiveProduction: 'Studio Mandacaru',
      imagePath: '7.png',
    },
    {
      name: 'Look Monocromático',
      collection: 'FW Streetwear',
      location: 'Avenida Paulista, SP',
      models: 'Leandro Silva',
      creativeDirection: 'Camila Lopes',
      photography: 'Rodrigo Santos',
      photographyAssistant: 'Alana Ribeiro',
      film: 'Lomography Color 800',
      styling: 'Cássia Ventura',
      beauty: 'Tati Brandão',
      setProduction: 'City Lights Studio',
      executiveProduction: 'Fashion Beats',
      imagePath: '8.png',
    },
    {
      name: 'Calça Cargo Feminina',
      collection: 'Neo Workwear',
      location: 'Porto Digital, Recife',
      models: 'Luana Martins',
      creativeDirection: 'Rafael Cunha',
      photography: 'Viviane Costa',
      photographyAssistant: 'Daniel Moreira',
      film: 'Ilford Delta 400',
      styling: 'Rodrigo Azevedo',
      beauty: 'Clarissa Lima',
      setProduction: 'Pernambuco Prod.',
      executiveProduction: 'Studio Rec',
      imagePath: '9.png',
    },
    {
      name: 'Vestido Assimétrico',
      collection: 'Gala 2025',
      location: 'Praia do Rosa, SC',
      models: 'Vitória Meireles',
      creativeDirection: 'Luísa Duarte',
      photography: 'Fábio Corrêa',
      photographyAssistant: 'Iara Mendes',
      film: 'Cinestill 50D',
      styling: 'Eduardo Pinto',
      beauty: 'Juliane Freitas',
      setProduction: 'Southwave Studio',
      executiveProduction: 'Alta Gala Prod.',
      imagePath: '10.png',
    },
    {
      name: 'Look com Tecido Reciclado',
      collection: 'Eco Future',
      location: 'Instituto Inhotim, MG',
      models: 'Gabriel Afonso',
      creativeDirection: 'Beatriz Ramos',
      photography: 'Natália Braga',
      photographyAssistant: 'André Vianna',
      film: 'Foma 100',
      styling: 'João Evaristo',
      beauty: 'Renata Lopes',
      setProduction: 'EcoProd Brasil',
      executiveProduction: 'Planeta Fashion',
      imagePath: '11.png',
    },
    {
      name: 'Blazer sem Gênero',
      collection: 'Genderless 2024',
      location: 'Centro de SP',
      models: 'Alex Lima',
      creativeDirection: 'Marcos Vicente',
      photography: 'Tatiana Soares',
      photographyAssistant: 'Samuel Brito',
      film: 'Kodak Tri-X 400',
      styling: 'Milena Rocha',
      beauty: 'Gabi Fernandes',
      setProduction: 'Neutro Co.',
      executiveProduction: 'Inclusiva Prod.',
      imagePath: '12.png',
    },
  ];