name: Deploy to GCP

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker to use Google Cloud Registry
        run: |
          gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64 -t gcr.io/adam-456215/photos-api ./backend --file ./backend/Dockerfile --push

      - name: Deploy to Google Cloud Run
        run: |
          npm run release
