name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set up Google Cloud credentials
        run: echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" | base64 --decode > google-service-account.json

      - name: Authenticate to Google Cloud
        run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > key.json

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker gcr.io --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        run: >
          docker buildx build --platform linux/amd64
          --tag gcr.io/adam-456215/photos-api
          --file ./backend/Dockerfile
          --push
          ./backend
      - name: Deploy to Google Cloud Run
        working-directory: ./backend
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BASE_URL: ${{ secrets.BASE_URL }}
          PORT: ${{ secrets.PORT }}
          API_URL: ${{ secrets.API_URL }}
          HOST: ${{ secrets.HOST }}
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: npm run release