name: Deploy Frontend to GCP

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project adam-456215

      - name: Configure Docker to use gcloud as a credential helper
        run: gcloud auth configure-docker gcr.io --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 \
            --tag gcr.io/adam-456215/farm-rio \
            --file ./web/Dockerfile \
            --push \
            ./web

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy farm-rio \
            --image gcr.io/adam-456215/next-app \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 3000
